platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

pod 'LlamaKit', :git => "https://github.com/ashfurrow/LlamaKit", :branch => "rac_podspec"
pod 'ReactiveCocoa', :git => "https://github.com/ashfurrow/ReactiveCocoa", :branch => "podspec"
pod 'Swift-RAC-Macros', :git => "https://github.com/ashfurrow/Swift-RAC-Macros"

target 'Tests', :exclusive => true do
  
  pod 'Quick', :git => "https://github.com/Quick/Quick"
  pod 'Nimble', :git => "https://github.com/Quick/Nimble"
  pod 'FBSnapshotTestCase', :head
  pod 'Nimble-Snapshots', :git => "https://github.com/ashfurrow/Nimble-Snapshots.git"

end
